### ISSUE TITLE
浮点型转换错误

### ISSUE THREAD

**Issue by waxiangzi** [ez8-co/xpjson#2]
当数据类型为浮点型时，有时候（比如为10.0）在json里可能是返回整形（10），但如果用浮点解析会报错，
建议不要报错:直接更优雅的自动转换为浮点型

**Comment by orca-zhang** [comment]
> 当数据类型为浮点型时，有时候（比如为10.0）在json里可能是返回整形（10），但如果用浮点解析会报错，
> 建议不要报错:直接更优雅的自动转换为浮点型

是解析还是获取呢～如果是获取的话，可以使用value.get\<float\>("key", 0.0)的方式优雅得获取噢。即使数据源是布尔值，或者字符串的数值，都是可以正常转换的噢，value.f()的方式只适用于已知固定类型的场景，不是非常建议使用的，原因如题，对端的处理逻辑可能导致序列化时，浮点数变成了整型或者字符串。

**Comment by waxiangzi** [comment]
谢谢解答！理解这个设计了。

**Comment by orca-zhang** [comment]
value.get\<float\>("key", 0.0)等价于value["key"].get\<float\>(0.0)
前者是object获取键值对的同时转换，后者是对值本身做转换
