### ISSUE TITLE
Using XPJSON on Linux ARM64 architecture

### ISSUE THREAD

**Issue by ILENIMARIUS** [ez8-co/xpjson#4]
Hello,
I tried to use this library on a Linux Arm64 platform but i cannot pass those errors:
 error: redefinition of ‘struct JSON::detail::json_is_integral_<long unsigned int>
previous definition of ‘struct JSON::detail::json_is_integral_<long unsigned int>
redefinition of ‘struct JSON::detail::json_is_integral_<long int>
previous definition of ‘struct JSON::detail::json_is_integral_<long int>
...
There are no issues with header guards.
Do you know if this library can run o this type of arch?

**Comment by orca-zhang** [comment]
> Hello,
> I tried to use this library on a Linux Arm64 platform but i cannot pass those errors:
> error: redefinition of ‘struct JSON::detail::json_is_integral_
> previous definition of ‘struct JSON::detail::json_is_integral_
> redefinition of ‘struct JSON::detail::json_is_integral_
> previous definition of ‘struct JSON::detail::json_is_integral_
> ...
> There are no issues with header guards.
> Do you know if this library can run o this type of arch?

Thanks for your feedback.
Which lines are the errors occurred？
137 & 138?
I think the macro condition should be adjust for Linux ARM64 architecture.

**Comment by zhengzxdgis** [comment]
anybody knows how to modify?

**Comment by orca-zhang** [comment]
Just have a try.
: )
